name: audio_player
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  just_audio: ^0.9.42
  permission_handler: ^11.3.1
  on_audio_query: ^2.9.0
  flutter_svg: ^2.0.16
  flutter_custom_tabs: ^2.1.0
  url_launcher: ^6.3.1
  # flutter_native_splash: ^2.2.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

# flutter_native_splash:
#   color: "#00141D"
#   image: assets/Launcher.png 
#   android: true
#   ios: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
